# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskowner',
            options={'ordering': ('time_assign',)},
        ),
    ]
