# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.AddField(
            model_name='task',
            name='owners',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='owned_tasks', through='task_management.TaskAssignedUser', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
        migrations.AlterField(
            model_name='task',
            name='criticality',
            field=models.SmallIntegerField(choices=[(2, 'High'), (1, 'Medium'), (0, 'Low')], default=1, verbose_name='Criticality'),
        ),
    ]
