# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0002_auto_20160411_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owners',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, through='task_management.TaskAssignedUser', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
    ]
