# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_auto_20160406_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdecline',
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskDecline',
        ),
    ]
