# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_auto_20160412_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactionlog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='taskactionlog',
            name='task',
        ),
        migrations.AddField(
            model_name='taskactionlog',
            name='action',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 13, 35, 31, 573922, tzinfo=utc), max_length=512, verbose_name='Action'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='owners',
            field=mptt.fields.TreeManyToManyField(blank=True, through='task_management.TaskAssignedUser', to=settings.AUTH_USER_MODEL, verbose_name='Owners'),
        ),
    ]
