# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0003_auto_20160406_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOwnerChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_assign', models.DateTimeField(auto_now_add=True)),
                ('assign_accept', models.NullBooleanField(verbose_name='Accept assign')),
                ('assign_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='task_management.TaskOwnerChain')),
            ],
            options={
                'ordering': ('time_assign',),
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taskowner',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='taskowner',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='taskowner',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskowner',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.DeleteModel(
            name='TaskOwner',
        ),
        migrations.AddField(
            model_name='taskownerchain',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_chain', to='task_management.Task'),
        ),
        migrations.AddField(
            model_name='taskownerchain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='taskownerchain',
            unique_together=set([('user', 'task')]),
        ),
    ]
