# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_auto_20160414_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskactionlog',
            old_name='time_action',
            new_name='time_create',
        ),
    ]
