# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096, verbose_name='Task title')),
                ('description', models.TextField(verbose_name='Task description')),
                ('status', models.SmallIntegerField(choices=[(0, 'Declined'), (1, 'Draft'), (2, 'Pending Acceptance'), (3, 'Working On It'), (4, 'Half Way Done'), (5, 'Almost Done'), (6, 'Completed')], verbose_name='Task status')),
                ('criticality', models.SmallIntegerField(choices=[(0, 'Low criticality'), (1, 'Medium criticality'), (2, 'High criticality')], verbose_name='Task criticality')),
                ('date_due', models.DateField(blank=True, null=True, verbose_name='Task due date')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time of create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Task assigned to')),
            ],
        ),
        migrations.CreateModel(
            name='TaskActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.SmallIntegerField(choices=[(0, 'Task create'), (1, 'Task change'), (2, 'Attachment upload'), (3, 'Sub task create'), (4, 'Task status change'), (5, 'Task comment')], verbose_name='Action type')),
                ('time_action', models.DateTimeField(auto_now_add=True, verbose_name='Time of action')),
                ('object_id', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='task_manage.Task', verbose_name='Action task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Comment message')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time of create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of comment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_manage.Task', verbose_name='Comment task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDecline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Reason for decline')),
                ('time_decline', models.DateTimeField(auto_now_add=True, verbose_name='Time of decline')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declines', to='task_manage.Task', verbose_name='Declined task')),
            ],
        ),
    ]
